#cache:
#  paths:
#    - /go/src/github.com
#    - /go/src/golang.org
#    - /go/src/google.golang.org
#    - /go/src/gopkg.in

stages:
  - test
  - build

unit_tests:
  stage: test
  image: golang:1.13
  script:
    - make test

race_detector:
  stage: test
  image: golang:1.13
  script:
    - make race

#code_coverage:
#  stage: test
#  image: golang:1.13
#  script:
#    - make coverage

#code_coverage_report:
#  stage: test
#  image: golang:1.13
#  script:
#    - make coverhtml
#  only:
#  - master

lint_code:
  stage: test
  image: golang:1.13
  script:
    - make lint

build:
  stage: build
  image: golang:1.13
  script:
    - apt install -y https://github.com/goreleaser/goreleaser/releases/download/v0.118.0/goreleaser_amd64.deb
    - make build
